---
- name: Create a management route to jumpbox
  delegate_to: localhost
  bigip_management_route:
    name: route_management_to_jumpbox
    gateway: "{{ extra_gw_management }}"
    network: "{{ extra_route_prefix_on_premise }}"
    state: present
    provider:
      user: "{{ extra_admin_user }}"
      password: "{{ extra_admin_password }}"
      server: "{{ extra_ip_mgt }}"
      server_port: "{{ extra_port_mgt }}"
      validate_certs: no

- name: onboarding SSLO - BIGIP - cluster config - master node
  uri:
    url: "https://{{ extra_ip_mgt }}/mgmt/shared/declarative-onboarding"
    method: "POST"
    user: "admin"
    password: "{{ extra_admin_password }}"
    validate_certs: no
    body: "{{ lookup('template', 'do-failover-5nic-master_node-BIGIQ.json') }}"
    body_format: json
    timeout: 300
    status_code: 200, 202
  register: json_response

- name: CMP_OUTPUT
  debug:
    msg: "
    key=do_log_file;value=/var/log/restnoded/restnoded.log;help=restnoded failure log;
    "
#######LOOP TO CHECK THE TASK - DO NOT MODIFY BELOW

- debug:
    var: json_response

- pause:
    prompt: "Please wait during f5 big-ip reboot"
    minutes: 10

...
