---
- name: CREATE vNIC Management
  delegate_to: localhost
  azure_rm_networkinterface:
    resource_group: "rg-{{ extra_platform_name }}"
    name: "nic-{{ extra_platform_name }}-{{ extra_vm_name }}-management"
    location: "{{ extra_location }}"
    virtual_network: "vnet-{{ extra_platform_name }}"
    subnet_name: "net-{{ extra_platform_name }}-management"
    create_with_security_group: false
    tags: "{{ extra_platform_tags }}
    Name=nic-{{ extra_platform_name }}-{{ extra_vm_name }}-management
    owner={{ owner }}"
    ip_configurations:
      - name: mgt
        private_ip_address: "{{ extra_ip_mgt }}"
        private_ip_allocation_method: 'Static'
        primary: true

- name: CREATE vNIC pan_dataplane as a pool member of pan_dataplane ILB
  delegate_to: localhost
  azure_rm_networkinterface:
    resource_group: "rg-{{ extra_platform_name }}"
    name: "nic-{{ extra_platform_name }}-{{ extra_vm_name }}-pan_dataplane"
    location: "{{ extra_location }}"
    virtual_network: "vnet-{{ extra_platform_name }}"
    subnet_name: "net-{{ extra_platform_name }}-pan_dataplane"
    create_with_security_group: false
    tags: "{{ extra_platform_tags }}
    Name=nic-{{ extra_platform_name }}-{{ extra_vm_name }}-pan_dataplane
    owner={{ owner }}"
    ip_configurations:
      - name: self_static
        private_ip_address: "{{ extra_ip_pan_dataplane }}"
        private_ip_allocation_method: 'Static'
        primary: true
        load_balancer_backend_address_pools:
          - name: "pool-{{ extra_cluster_name }}-pan_dataplane"
            load_balancer: "ilb-{{ extra_platform_name }}"
    enable_ip_forwarding: true

- name: CREATE a storage account
  delegate_to: localhost
  azure_rm_storageaccount:
    resource_group: "rg-{{ extra_platform_name }}"
    location: "{{ extra_location }}"
    name: "pan{{ extra_vm_name }}data000"
    type: Standard_LRS
    kind: Storage
    https_only: true
    tags: "{{ extra_platform_tags }}
      Name={{ extra_vm_name }}
      owner={{ owner }}"

- name: CREATE VM PAN FW - PAN
  delegate_to: localhost
  azure_rm_virtualmachine:
    resource_group: "rg-{{ extra_platform_name }}"
    name: "{{ extra_vm_name }}"
    location: "{{ extra_location }}"
    short_hostname: "{{ extra_vm_name }}"
    vm_size: "Standard_DS3_v2"
    os_disk_size_gb: 512
    tags: "{{ extra_platform_tags }}
              Name={{ extra_vm_name }}
              owner={{ owner }}
              zone={{ extra_zone_name }}"
    admin_username: "{{ infra_admin_username }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/{{ infra_admin_username }}/.ssh/authorized_keys"
        key_data: "{{ extra_key_data }}"
    image:
      offer: vmseries1
      publisher: paloaltonetworks
      sku: bundle2
      version: 9.0.4
    plan:
      name: bundle2
      product: vmseries1
      publisher: paloaltonetworks
    managed_disk_type: Standard_LRS
    os_type: Linux
    storage_account_name: "pan{{ extra_vm_name }}data000"
    network_interface_names:
      - "nic-{{ extra_platform_name }}-{{ extra_vm_name }}-management"
      - "nic-{{ extra_platform_name }}-{{ extra_vm_name }}-pan_dataplane"
    zones: ['{{ extra_availability_zone }}']






...