---
- name: Create VRF Internal, in, out, dataplane
  delegate_to: localhost
  azure_rm_routetable:
    resource_group: "rg-{{ extra_platform_name }}"
    location: "{{ extra_location }}"
    name: "rt-{{ extra_platform_name }}-{{ item }}"
    disable_bgp_route_propagation: True
    tags: "{{ extra_platform_tags }} Name=rt-{{ extra_platform_name }}-{{ item }} owner={{ owner }}"
  loop: "{{ design_hub.vrf }}"

- name: Create Subnet external
  delegate_to: localhost
  azure_rm_subnet:
    resource_group: "rg-{{ extra_platform_name }}"
    virtual_network: "vnet-{{ extra_platform_name }}"
    name: "net-{{ extra_platform_name }}-external"
    address_prefix: "{{ extra_external_subnet_address_prefix }}"
    security_group_name: "nsg-{{ extra_platform_name }}-external"
    route_table: "rt-{{ extra_platform_name }}-external"

- name: Create Subnet internal
  delegate_to: localhost
  azure_rm_subnet:
    resource_group: "rg-{{ extra_platform_name }}"
    virtual_network: "vnet-{{ extra_platform_name }}"
    name: "net-{{ extra_platform_name }}-internal"
    address_prefix: "{{ extra_internal_subnet_address_prefix }}"
    security_group_name: "nsg-{{ extra_platform_name }}-internal"
    route_table: "rt-{{ extra_platform_name }}-internal"

- name: Create Subnet sslo_inbound
  delegate_to: localhost
  azure_rm_subnet:
    resource_group: "rg-{{ extra_platform_name }}"
    virtual_network: "vnet-{{ extra_platform_name }}"
    name: "net-{{ extra_platform_name }}-sslo_inbound"
    address_prefix: "{{ extra_sslo_inbound_subnet_address_prefix }}"
    security_group_name: "nsg-{{ extra_platform_name }}-internal"
    route_table: "rt-{{ extra_platform_name }}-sslo_inbound"

- name: Create Subnet sslo_outbound
  delegate_to: localhost
  azure_rm_subnet:
    resource_group: "rg-{{ extra_platform_name }}"
    virtual_network: "vnet-{{ extra_platform_name }}"
    name: "net-{{ extra_platform_name }}-sslo_outbound"
    address_prefix: "{{ extra_sslo_outbound_subnet_address_prefix }}"
    security_group_name: "nsg-{{ extra_platform_name }}-internal"
    route_table: "rt-{{ extra_platform_name }}-sslo_outbound"

- name: Create Subnet pan_dataplane
  delegate_to: localhost
  azure_rm_subnet:
    resource_group: "rg-{{ extra_platform_name }}"
    virtual_network: "vnet-{{ extra_platform_name }}"
    name: "net-{{ extra_platform_name }}-pan_dataplane"
    address_prefix: "{{ extra_pan_dataplane_subnet_address_prefix }}"
    security_group_name: "nsg-{{ extra_platform_name }}-internal"
    route_table: "rt-{{ extra_platform_name }}-pan_dataplane"












...