---
- name: List VM instances in Virtual Machine ScaleSet
  delegate_to: localhost
  azure_rm_virtualmachinescalesetinstance_info:
    resource_group: "rg-{{ extra_platform_name }}"
    vmss_name: "{{ extra_vmss_name }}"
  register: list_vmss_instances

- name: INIT list_instance_id
  set_fact:
    list_instance_id: []

- name: GET VM instance_id
  set_fact:
    list_instance_id: "{{ list_instance_id }} + [{{ item.instance_id }}]"
  loop: "{{ list_vmss_instances.instances }}"
  register: list_instance_id

- name: GET NIC management
  delegate_to: localhost
  azure_rm_networkinterface_vmss_info:
    resource_group_name: "rg-{{ extra_platform_name }}"
    virtual_machine_scale_set_name: "{{ extra_vmss_name }}"
    virtualmachine_index: "{{ item.instance_id }}"
    network_interface_name: "{{ extra_vmss_name }}-management"
  loop: "{{ list_vmss_instances.instances }}"
  register: list_nic_awaf_management

- name: GET NIC dataplane
  delegate_to: localhost
  azure_rm_networkinterface_vmss_info:
    resource_group_name: "rg-{{ extra_platform_name }}"
    virtual_machine_scale_set_name: "{{ extra_vmss_name }}"
    virtualmachine_index: "{{ item.instance_id }}"
    network_interface_name: "{{ extra_vmss_name }}-dataplane"
  loop: "{{ list_vmss_instances.instances }}"
  register: list_nic_awaf_dataplane

- name: INIT var
  set_fact:
    var_self_ips: []

- name: SET var_self_ips
  set_fact:
    var_self_ips: "{{ var_self_ips }} + [{
      'instance_id': '{{ list_instance_id[cur_index] }}',
      'management': '{{ item.0.networkinterfaces[0].ip_configurations[0].private_ip_address }}',
      'dataplane': '{{  item.1.networkinterfaces[0].ip_configurations[0].private_ip_address }}',
    }]"
  loop: "{{ list_nic_awaf_management.results|zip(list_nic_awaf_dataplane.results)|list }}"
  loop_control:
    index_var: cur_index

- name: SHOW var_self_ips
  debug:
    msg: "var_self_ips: {{ var_self_ips }}
    "

- name: "Artifact for Tower Workflows"
  set_stats:
    data:
      stats_self_ips:  "{{ var_self_ips }}"








...
